CIRCUITPY_WIFI_SSID = "<YOURWIFI-SSID>"
CIRCUITPY_WIFI_PASSWORD = "YOURWIFI-SSID-PASSWORD"
CIRCUITPY_WEB_API_PORT = 80
CIRCUITPY_WEB_API_PASSWORD = "passw0rd"
test_variable = "this is a test"
thumbs_up = "\U0001f44d"
ADAFRUIT_AIO_USERNAME = "YOUR ADAFRUIT IO USERNAME"
ADAFRUIT_AIO_KEY      = "YOUR ADAFRUIT IO API KEY"